name: Create production promotion pull request
on:
  push:
    branches:
      #- gh-pages
      - 'feature/*'
      - 'develop'

jobs:
  create-pull-request:
        runs-on: ubuntu-latest
        run: |
          echo " ${{ github.ref }}"
