name: Create production promotion pull request
on:
  push:
    branches:
      #- gh-pages
      - 'feature/*'
      - 'develop'

jobs:
  create-pull-request:
        runs-on: ubuntu-latest
        if: ${{ github.ref}} == 'refs/heads/feature/* '
        steps:
          - name: Doing Test
            run: |
              echo "Testing ${{ github.ref }}"
              echo "Test Succesfull"
          - name: Check out repository code
            uses: actions/checkout@v2
          - name: pull-request
            uses: repo-sync/pull-request@v2
            with:
              destination_branch: "develop"
              github_token: ${{ secrets.GITHUB_TOKEN }}
              pr_label: "feature, automated pr"
              pr_title: "Pull request ${{ github.ref }} into develop"

        if: ${{ github.ref}} == 'refs/heads/develop '
        steps:
          - name: Doing Test
            run: |
              echo "Testing ${{ github.ref }}"
              echo "Test Succesfull"
          - name: Check out repository code
            uses: actions/checkout@v2
          - name: pull-request
            uses: repo-sync/pull-request@v2
            with:
              destination_branch: "main"
              github_token: ${{ secrets.GITHUB_TOKEN }}
              pr_label: "feature, automated pr"
              pr_title: "Pull request ${{ github.ref }} into main"
